config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions'}
  resources :people
  root 'people#index'
  resources :profiles do
    member do
      post 'change_status'
    end
  end
  resources :addresses
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :person
  validates_presence_of :first_name, :last_name, :gender, :email
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]


  def index
    @profiles = Profile.all
  end

  def change_status
    profile = Profile.find( params[:id])
    profile.active = !profile.active
    if profile.save
      flash[:notice] = "#{profile.first_name} has been #{profile.active ? 'activated' : 'deactivated'}"
    else
      flash[:error]= profile.errors.full_messages.to_sentence
    end
    respond_to do |format|
      format.js {head :ok}
    end
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)

      if @profile.save
        flash[:notice] = 'Profile was successfully created.'
        redirect_to @profile
      else
        flash[:error]= @profile.errors.full_messages.to_sentence
        redirect_to new_profile_path
      end
  end

  def update
      if @profile.update(profile_params)
        flash[:notice] = 'Profile was successfully updated.'
        redirect_to @profile
      else
        flash[:error]= @profile.errors.full_messages.to_sentence
        redirect_to edit_profile_path
      end
  end

  def destroy
    @profile.destroy
      flash[:notice] = 'Profile was successfully destroyed.'
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :gender, :email, :person_id, :active)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |form|
  .row
    .col-sm-6
      .card
        .card-body
          
          .form-group.row
            .col-sm-8
              = form.text_field :first_name, placeholder: "First Name", class: 'form-control'

          .form-group.row
            .col-sm-8
              = form.text_field :last_name, placeholder: "Last Name", class: 'form-control'

          .form-group.row
            .col-sm-8
              = form.email_field :email, placeholder: "Enter email", class: 'form-control'
              %small#emailHelp.form-text.text-muted We'll never share your email with anyone else.

          .form-group.row
            %label.col-sm-2.col-form-label{for: "text"} Person
            .col-sm-10
              = form.collection_select :person_id, Person.order(:name),:id,:name, class: "form-control", include_blank: true

          .form-group.row
            %label.col-sm-2.col-form-label{for: "text"} Gender
            .col-sm-10
              = form.select :gender,['Male', 'Female'], class:"btn btn-secondary dropdown-toggle", include_blank: true

          .form-group.row
            %label.col-sm-2.col-form-label{for: "text"} Status
            .col-sm-10
              .radio
                = form.radio_button :active,true
                Active
                = form.radio_button :active,false
                Inactive

          .actions
            = form.submit"create profile", class:"btn btn-outline-secondary"
            = link_to 'Back', profiles_path, class:"btn btn-outline-secondary"

:javascript
  $('select').select2(); 

app/views/profiles/edit.html.haml
%h1 Editing Profile
= render 'form', profile: @profile

app/views/profiles/index.html.haml
%h1 Profiles

.card
  .card-body
    %table.table.table-striped.table-hover
      %thead.thead-dark
        %tr
          %th First name
          %th Last name
          %th Gender
          %th Email
          %th Person
          %th Status
          %th{colspan: "3"}
      %tbody
        - @profiles.each do |profile|
          %tr.table-light
            %td= profile.first_name
            %td= profile.last_name
            %td= profile.gender
            %td= profile.email
            %td= profile.person.name
            %td
              - if profile.active
                %input{checked: 'checked',class: 'profile_check', id: profile.id, data: { toggle: 'toggle', off: 'deactivated', on: 'activated'}, onclick: "change_status(#profile.id)", type: 'checkbox'}
              - else
                %input{ data: { toggle: 'toggle', off: 'deactivated', on: 'activated'}, class: 'profile_check', id: "#{profile.id}", onclick: "change_status(#profile.id)", type: 'checkbox'}
            %td= link_to 'Show', profile, class:"btn btn-outline-secondary"
            %td= link_to 'Edit', edit_profile_path(profile), class:"btn btn-outline-secondary"
            %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger"
%br/
= link_to 'New Profile', new_profile_path, class:"btn btn-outline-secondary"

app/views/profiles/new.html.haml
%h1 New Profile
= render 'form', profile: @profile

app/views/profiles/show.html.haml
%br
%p
  %a.btn.btn-primary{"aria-controls" => "multiCollapseExample1", "aria-expanded" => "false", "data-toggle" => "collapse", href: "#multiCollapseExample1", role: "button"} Show My Profile 
.row
  .col
    #multiCollapseExample1.collapse.multi-collapse
      .card.card-body
        %p
          %strong First name:
          = @profile.first_name
        %p
          %strong Last name:
          = @profile.last_name
        %p
          %strong Gender:
          = @profile.gender
        %p
          %strong Email:
          = @profile.email
        %p
          %strong Person:
          = @profile.person.name
        %p
          %strong Status:
          = @profile.active
      %br    
      = link_to 'Edit', edit_profile_path(@profile), class:"btn btn-outline-secondary"
%br      
= link_to 'Back', profiles_path, class:"btn btn-outline-secondary"