config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions'}
  resources :people
  root 'people#index'
  resources :profiles do
    member do
      post 'change_status'
    end
  end
  resources :addresses
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :addresses
  has_one :profile
  validates_presence_of :name, :date_of_birth, :phone_number

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: PeopleDatatable.new(view_context) }
    end
  end

  def show
  end

  def new
    @person = Person.new
  end


  def edit
  end

  def create
    @person = Person.new(person_params)

      if @person.save
        flash[:notice] = 'Person was successfully created.'
        redirect_to @person
      else
        flash[:error]= @person.errors.full_messages.to_sentence
        redirect_to new_person_path
        render  error: person.errors.full_messages
      end
  end


  def update
      if @person.update(person_params)
        flash[:notice] = 'Person was successfully updated.'
        redirect_to @person
      else
        flash[:error]= @person.errors.full_messages.to_sentence
        redirect_to edit_person_path
      end
  end

  def destroy
    @person.destroy
      flash[:notice] = 'Person was successfully destroyed.'
  end

  private
    def set_profile
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :date_of_birth, :phone_number)
    end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= form_for @person do |form|

  .row
    .col-sm-6
      .card
        .card-body
          .form-group.row
            .col-sm-8
              .form-group.row
                .col-sm-8
                  = form.text_field :name, id: :person_name, placeholder: "Name", class: 'form-control'
              .form-group.row
                .col-sm-8
                  = form.text_field :date_of_birth, id: :person_date_of_birth, placeholder: "Date Of Birth", class: 'form-control'
              .form-group.row
                .col-sm-8
                  = form.text_field :phone_number, id: :person_phone_number, placeholder: "Phone Number", class: 'form-control'
              .actions
                = form.submit"create person", class:"btn btn-outline-secondary"

app/views/people/edit.html.haml
%h1 Editing Person
= render 'form', person: @person
= link_to 'Show', @person, class:"btn btn-outline-secondary"
= link_to 'Back', people_path, class:"btn btn-outline-secondary"

app/views/people/index.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
  %body

    %nav.navbar.navbar-expand-lg.navbar-light
      %a.navbar-brand{href: "#"} 
        %span Elite
        %span Corp

      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar", "data-toggle" => "collapse", type: "button" }
        %span.navbar-toggler-icon
      #navbar.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
 
          %li.nav-item
            %a.nav-link{href: "#about"} About

          %li.nav-item
            %a.nav-link{href: "#work"} Work

          %li.nav-item
            %a.nav-link{href: "#contactus"} Contact          
          
    
    .slider
      #carouselExampleIndicators.carousel.slide{"data-ride" => "carousel"}
        %ol.carousel-indicators
          %li.active{"data-slide-to" => "0", "data-target" => "#carouselExampleIndicators"}
          %li{"data-slide-to" => "1", "data-target" => "#carouselExampleIndicators"}
          %li{"data-slide-to" => "2", "data-target" => "#carouselExampleIndicators"}
        .carousel-inner
          %h1 
            We're an Independent
            %br
            Design and  
            %span>   Development
            %br 
            Agency
          .overlay

          .carousel-item.active
            %img.d-block.w-100{:alt => "First slide", :src => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8sTYV7AO0Fy1F8cfJ7itcRpXuAJlz_7z3_U3UCLKWfHp4LmQi"}
          .carousel-item
            %img.d-block.w-100{:alt => "Second slide", :src => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8sTYV7AO0Fy1F8cfJ7itcRpXuAJlz_7z3_U3UCLKWfHp4LmQi"}/
          .carousel-item
            %img.d-block.w-100{:alt => "Third slide", :src => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8sTYV7AO0Fy1F8cfJ7itcRpXuAJlz_7z3_U3UCLKWfHp4LmQi"}/



    .datatable
      %table.table.table-striped.table-bordered.table-hover#person.display{data: {source: people_url(format: 'json')}}
        %thead.thead-dark
          %tr
            %th Name
            %th Date Of Birth
            %th Phone Number
        %tbody


    .features.text-center#work
      .row
        .col-sm-6.col-lg-3
          %i.fa.fa-github.fa-3x.rounded-circle
          %h3 Great Idea
          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

        .col-sm-6.col-lg-3
          %i.fa.fa-github.fa-3x.rounded-circle
          %h3 Great Idea
          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

        .col-sm-6.col-lg-3
          %i.fa.fa-github.fa-3x.rounded-circle
          %h3 Great Idea
          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

        .col-sm-6.col-lg-3
          %i.fa.fa-github.fa-3x.rounded-circle
          %h3 Great Idea
          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua


    .overview.text-center#about
      %h2.h1 Company overview
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
      %h4 Lets Start Today
      %a.btn.btn-primary{"aria-controls" => "multiCollapseExample1", "aria-expanded" => "false", "data-toggle" => "collapse", href: "#multiCollapseExample1", role: "button"} View More 
      .row
        .col
          #multiCollapseExample1.collapse.multi-collapse
            
            %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 


    .footer#contactus
      .row
        .col-md-4
          .site-info
            %span Elite
            %span Corp

            %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua



        .col-md-4
          .helpful-links
            %h2 Helpful Links
            .row
              .col
                %ul.list-unstyled
                  %li About
                  %li Portofolio
                  %li Team
                  %li Price
                  %li Privacy

              .col
                %ul.list-unstyled
                  %li FAQ
                  %li Blog
                  %li How it works
                  %li Benefits
                  %li Contact


        .col-md-4
          .contact
            %h2 Contact Us 
            %ul.list-unstyled
              %li Address:
              %li Phone:
              %li Email:  


      
        

%script
  $('.carousel').carousel()    

app/views/people/new.html.haml
%h1 New Person
= render 'form', person: @person
= link_to 'Back', people_path, class:"btn btn-outline-secondary"

app/views/people/show.html.haml
%br
.row
  .col-sm-6
    .card
      .card-body
        %p
          %a{ class:"btn btn-secondary","aria-controls" => "collapseOne", "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
            Address
            %span.badge.badge-pill.badge-light= @person.addresses.count
        %p
          %strong Name:
          = @person.name
        %p
          %strong Date of birth:
          = @person.date_of_birth
        %p
          %strong Phone number:
          = @person.phone_number
        %br          
        = link_to 'Edit', edit_person_path(@person), class:"btn btn-outline-secondary"
        = link_to 'Back', people_path, class:"btn btn-outline-secondary"