config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions'}
  resources :people
  root 'people#index'
  resources :profiles do
    member do
      post 'change_status'
    end
  end
  resources :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:country, :city, :person_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.haml
= form_for @address do |form|

  .row
    .col-sm-6
      .card
        .card-body
          .form-group.row
            .col-sm-8
              = form.text_field :country, placeholder: "Country", class: 'form-control'

          .form-group.row
            .col-sm-8
              = form.text_field :city, placeholder: "City", class: 'form-control'

          .form-group.row
            %label.col-sm-2.col-form-label{for: "text"} Person
            .col-sm-10
              = form.collection_select :person_id, Person.order(:name),:id,:name, class: "form-control", include_blank: true

          .actions
            = form.submit"create address", class:"btn btn-outline-secondary"
            = link_to 'Back', addresses_path, class:"btn btn-outline-secondary"

:javascript
  $('select').select2();          

app/views/addresses/edit.html.haml
%h1 Editing Address
= render 'form', address: @address

app/views/addresses/index.html.haml
%h1 Addresses

.card
  .card-body
    %table.table.table-striped.table-bordered.table-hover
      %thead.thead-dark
        %tr
          %th Country
          %th City
          %th Person
          %th{colspan: "3"}
      %tbody
        - @addresses.each do |address|
          %tr.table-light
            %td= address.country
            %td= address.city
            %td= address.person.name
            %td= link_to 'Show', address, class:"btn btn-outline-secondary"
            %td= link_to 'Edit', edit_address_path(address), class:"btn btn-outline-secondary"
            %td= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger"
%br/
= link_to 'New Address', new_address_path, class:"btn btn-outline-secondary"

app/views/addresses/new.html.haml
%h1 New Address
= render 'form', address: @address

app/views/addresses/show.html.haml
%br
.row
  .col-sm-6
    .card
      .card-body
        %p
          %strong Country:
          = @address.country
        %p
          %strong City:
          = @address.city
        %p
          %strong Person:
          = @address.person.name
        %br          

        = link_to 'Edit', edit_address_path(@address), class:"btn btn-outline-secondary"
        = link_to 'Back', addresses_path, class:"btn btn-outline-secondary"



  